import { readFile } from 'node:fs/promises';
import { expect, test } from '@playwright/test';
import { createTask, navigate, openWorkspace, persistedState, taskCard, uniqueName } from './helpers';

test('registration migrates guest data, profile edits persist, export works, and the new password logs in', async ({ page }) => {
  const taskName = uniqueName('游客的第一步');
  const username = uniqueName('walker');
  const renamed = `${username}_new`;
  const originalPassword = 'A-private-test-password-101';
  const newPassword = 'A-private-test-password-202';
  await openWorkspace(page);
  await createTask(page, taskName, { target: 3 });
  await navigate(page, '个人中心');
  await page.getByRole('tab', { name: '注册', exact: true }).click();
  await page.getByLabel('用户名', { exact: true }).fill(username);
  await page.getByLabel('密码', { exact: true }).fill(originalPassword);
  await page.getByRole('button', { name: '创建账号', exact: true }).click();
  await expect(page.getByRole('button', { name: '退出登录', exact: true })).toBeVisible();
  let state = await persistedState(page);
  expect(state.tasks.find(task => task.name === taskName)?.owner_id).toMatch(/^user:/);
  await page.getByLabel('用户名', { exact: true }).fill(renamed);
  await page.getByRole('button', { name: '保存资料', exact: true }).click();
  await expect(page.getByRole('heading', { name: renamed, exact: true })).toBeVisible();
  await page.getByLabel('当前密码', { exact: true }).fill(originalPassword);
  await page.getByLabel('新密码', { exact: true }).fill(newPassword);
  await page.getByRole('button', { name: '更新密码', exact: true }).click();
  await expect(page.getByText('密码已更新', { exact: true })).toBeVisible();
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '导出数据', exact: true }).click();
  const download = await downloadPromise;
  expect(download.suggestedFilename()).toMatch(/^pawnsteps-.*\.json$/);
  const exportData = JSON.parse(await readFile((await download.path())!, 'utf8'));
  expect(exportData.tasks.some((task: { name: string }) => task.name === taskName)).toBe(true);
  await page.getByRole('button', { name: '退出登录', exact: true }).click();
  await expect(page.getByRole('tab', { name: '账号登录', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: '账号登录', exact: true }).click();
  await page.getByLabel('账号或邮箱', { exact: true }).fill(renamed);
  await page.getByLabel('密码', { exact: true }).fill(newPassword);
  await page.getByRole('button', { name: '登录', exact: true }).click();
  await expect(page.getByRole('button', { name: '退出登录', exact: true })).toBeVisible();
  await navigate(page, '我的任务');
  await expect(taskCard(page, taskName)).toBeVisible();
  state = await persistedState(page);
  expect(state.stats.total).toBe(1);
});

test('admin credentials use the separate workspace and inspect user data', async ({ page }) => {
  test.skip(!process.env.E2E_ADMIN_USERNAME || !process.env.E2E_ADMIN_PASSWORD, 'Supply dedicated test administrator credentials to exercise the admin UI.');
  await page.goto('/admin');
  await page.getByLabel('管理员账号', { exact: true }).fill(process.env.E2E_ADMIN_USERNAME!);
  await page.getByLabel('密码', { exact: true }).fill(process.env.E2E_ADMIN_PASSWORD!);
  await page.getByRole('button', { name: '登录管理后台', exact: true }).click();
  await expect(page.getByRole('heading', { name: /所有用户/ })).toBeVisible();
  await page.getByRole('button', { name: '查看', exact: true }).first().click();
  await expect(page.getByRole('button', { name: '导出用户数据', exact: true })).toBeVisible();
  expect(await page.evaluate(() => Boolean(localStorage.getItem('pawnsteps-token')))).toBe(false);
  await page.getByRole('button', { name: '退出管理员', exact: true }).click();
  await expect(page.getByRole('button', { name: '登录管理后台', exact: true })).toBeVisible();
});
