import { expect, test } from '@playwright/test';
import path from 'node:path';
import { createTask, navigate, openCourse, openRecords, openWorkspace, persistedState, recordProgress, showCompletedTasks, taskCard, uniqueName } from './helpers';

test.beforeEach(async ({ page }) => { await openWorkspace(page); });

test('ordinary progress unlocks its reward, updates XP, and deletion can be undone', async ({ page }) => {
  const rewardName = uniqueName('周末电影');
  const taskName = uniqueName('整理阅读笔记');
  await navigate(page, '心愿奖励');
  await page.getByRole('button', { name: '添加奖励', exact: true }).click();
  const rewardDialog = page.getByRole('dialog', { name: '添加一个小期待' });
  await rewardDialog.getByLabel('奖励名称', { exact: true }).fill(rewardName);
  await rewardDialog.getByRole('button', { name: '添加奖励', exact: true }).click();
  await expect(rewardDialog).toBeHidden();
  await expect(page.getByRole('heading', { name: rewardName, exact: true })).toBeVisible();
  await navigate(page, '我的任务');
  await createTask(page, taskName, { target: 2, reward: rewardName });
  await recordProgress(page, taskName, 1, '先整理目录');
  await page.keyboard.press('Escape');
  await expect.poll(async () => (await persistedState(page)).tasks.find(task => task.name === taskName)?.progress).toBe(1);
  await recordProgress(page, taskName, 1, '完成最后的整理');
  await page.keyboard.press('Escape');
  const celebration = page.getByRole('dialog', { name: '一个心愿，解锁了。' });
  await expect(celebration).toContainText(rewardName);
  await celebration.getByRole('button', { name: '收下这份奖励' }).click();
  const rewardCard = page.locator('article.reward-card').filter({ has: page.getByRole('heading', { name: rewardName, exact: true }) });
  await expect(rewardCard).toContainText('已解锁');
  const state = await persistedState(page);
  expect(state.stats.xp).toBe(100);
  expect(state.tasks.find(task => task.name === taskName)?.is_done).toBe(true);
  await navigate(page, '我的任务');
  await showCompletedTasks(page);
  await taskCard(page, taskName).getByRole('button', { name: `任务操作：${taskName}`, exact: true }).click();
  await page.getByRole('menuitem', { name: `删除${taskName}`, exact: true }).click();
  await expect(taskCard(page, taskName)).toHaveCount(0);
  await page.locator('[data-sonner-toast]').filter({ hasText: '任务已删除' }).getByRole('button', { name: '撤销', exact: true }).click();
  await expect(taskCard(page, taskName)).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: '已完成任务', exact: true })).toHaveAttribute('aria-expanded', 'false');
  await showCompletedTasks(page);
  await expect(taskCard(page, taskName)).toBeVisible();
  expect((await persistedState(page)).stats.xp).toBe(100);
});

test('daily entries count one day, revoking a record reopens the day, and the remainder persists', async ({ page }) => {
  const name = uniqueName('每天读书');
  await createTask(page, name, { kind: 'daily', target: 7, quota: 2, unit: '页' });
  await recordProgress(page, name, 1, '早上读一页');
  await page.keyboard.press('Escape');
  const dialog = await recordProgress(page, name, 1, '晚上再读一页');
  await expect(dialog.getByRole('article')).toHaveCount(2);
  let state = await persistedState(page);
  expect(state.tasks[0].daily_progress).toBe(2);
  expect(state.tasks[0].progress).toBe(1);
  expect(state.stats.streak).toBe(1);
  await dialog.getByRole('article').filter({ hasText: '晚上再读一页' }).getByRole('button', { name: '撤销记录', exact: true }).click();
  await expect(dialog.getByRole('article')).toHaveCount(1);
  await page.keyboard.press('Escape');
  await expect(taskCard(page, name)).toContainText('今日 1 / 2 页');
  await page.reload();
  await expect(taskCard(page, name)).toBeVisible();
  state = await persistedState(page);
  expect(state.tasks[0].daily_done).toBe(false);
  expect(state.tasks[0].progress).toBe(0);
  expect(state.tasks[0].today_amount).toBe(1);
  expect(state.tasks[0].record_count).toBe(1);
  expect(state.stats.streak).toBe(0);
});

test('a planned rest day is marked complete while positive quotas define the total', async ({ page }) => {
  const name = uniqueName('有节奏的计划');
  await createTask(page, name, { kind: 'plan', plan: '0, 10, -1, 5' });
  await expect(taskCard(page, name)).toContainText('今日休息');
  const task = (await persistedState(page)).tasks.find(task => task.name === name)!;
  expect(task.target).toBe(15);
  expect(task.progress).toBe(0);
  expect(task.daily_done).toBe(true);
  expect(task.is_done).toBe(false);
  await expect(taskCard(page, name).getByRole('slider')).toHaveCount(0);
  const dialog = await openRecords(page, name);
  await expect(dialog.getByRole('button', { name: '保存记录', exact: true })).toHaveCount(0);
  await page.keyboard.press('Escape');
});

test('Markdown course import excludes folders and supports item and chapter completion', async ({ page }) => {
  const name = uniqueName('系统课程');
  await page.getByRole('button', { name: '添加任务', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '从一个小目标开始' });
  await dialog.getByRole('button', { name: /^课程学习/ }).click();
  await dialog.getByLabel('任务名称', { exact: true }).fill(name);
  await dialog.locator('input[type="file"][accept]').setInputFiles({ name: 'course.md', mimeType: 'text/markdown', buffer: Buffer.from('### Foundations\n- Lesson 1\n- Lesson 2\n### Practice\n* Final project\n', 'utf8') });
  await expect(dialog).toContainText('3 节课程');
  await dialog.getByRole('button', { name: '创建任务', exact: true }).click();
  const card = taskCard(page, name);
  await expect(card).toContainText('0 / 3 节');
  await expect(card.getByRole('checkbox')).toHaveCount(0);
  let drawer = await openCourse(page, name);
  await expect(drawer.getByRole('button', { name: 'Foundations 0/2', exact: true })).toHaveAttribute('aria-expanded', 'true');
  await expect(drawer.getByRole('button', { name: 'Practice 0/1', exact: true })).toHaveAttribute('aria-expanded', 'false');
  await drawer.getByText('Lesson 1', { exact: true }).click();
  await expect(drawer.getByRole('checkbox', { name: 'Lesson 1', exact: true })).toBeChecked();
  await expect(card).toContainText('1 / 3 节');
  await drawer.getByRole('button', { name: '完成Foundations全部条目', exact: true }).click();
  await expect(card).toContainText('2 / 3 节');
  await page.keyboard.press('Escape');
  await expect(drawer).toBeHidden();
  await expect(card.getByRole('button', { name: `${name}继续学习`, exact: true })).toBeFocused();
  drawer = await openCourse(page, name);
  await expect(drawer.getByRole('button', { name: 'Practice 0/1', exact: true })).toHaveAttribute('aria-expanded', 'true');
  await drawer.getByRole('button', { name: '完成Practice全部条目', exact: true }).click();
  await expect(drawer).toBeVisible();
  await expect(drawer).toContainText('课程已完成');
  const state = await persistedState(page);
  const task = state.tasks.find(task => task.name === name)!;
  expect(task.target).toBe(3);
  expect(task.progress).toBe(3);
  expect(task.course_items?.filter(item => item.name.endsWith('/')).every(item => !item.done)).toBe(true);
  expect(state.stats.xp).toBe(100);
  await page.keyboard.press('Escape');
  await expect(drawer).toBeHidden();
  const completed = page.getByRole('button', { name: '已完成任务', exact: true });
  await expect(completed).toBeFocused();
  await completed.press('Enter');
  await expect(card).toHaveCount(1);
  await expect(card).toBeVisible();
});

test('keyboard drag sorting persists unfinished task order', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 1400 });
  const first = uniqueName('第一项');
  const second = uniqueName('第二项');
  await createTask(page, first, { target: 5 });
  await createTask(page, second, { target: 5 });
  const initialState = await persistedState(page);
  const firstId = initialState.tasks.find(task => task.name === first)!.id;
  const secondId = initialState.tasks.find(task => task.name === second)!.id;
  const handle = taskCard(page, first).getByRole('button', { name: `拖动排序${first}`, exact: true });
  await handle.focus();
  await page.keyboard.press('Space');
  await expect(handle).toHaveAttribute('aria-pressed', 'true');
  await expect(page.getByRole('status')).toContainText(`droppable area ${firstId}`);
  await page.evaluate(() => new Promise<void>(resolve => requestAnimationFrame(() => requestAnimationFrame(() => resolve()))));
  await page.keyboard.press('ArrowDown');
  await expect(page.getByRole('status')).toContainText(`droppable area ${secondId}`);
  await page.keyboard.press('Space');
  await expect(handle).not.toHaveAttribute('aria-pressed', 'true');
  await expect.poll(async () => (await persistedState(page)).tasks.map(task => task.name)).toEqual([second, first]);
  await expect(handle).toBeFocused();
  await page.reload();
  await expect(page.locator('article.task-card h3')).toHaveText([second, first]);
});

test('read-only progress cannot change totals while records remain editable after completion', async ({ page }) => {
  const name = uniqueName('记录阅读进展');
  await createTask(page, name, { target: 5, unit: '页' });
  const card = taskCard(page, name);
  const progress = card.getByRole('progressbar', { name: `${name}总进度`, exact: true });
  await expect(card.getByRole('slider')).toHaveCount(0);
  await expect(card.getByRole('button', { name: `${name}减少1页`, exact: true })).toBeDisabled();
  for (const amount of [1, 5]) await expect(card.getByRole('button', { name: `${name}增加${amount}页`, exact: true })).toBeVisible();
  const writes: string[] = [];
  const observe = (request: import('@playwright/test').Request) => {
    if (new URL(request.url()).pathname.startsWith('/api/tasks/') && request.method() !== 'GET') writes.push(request.method());
  };
  page.on('request', observe);
  const bounds = (await progress.boundingBox())!;
  await page.mouse.move(bounds.x + 2, bounds.y + bounds.height / 2);
  await page.mouse.down();
  await page.mouse.move(bounds.x + bounds.width - 2, bounds.y + bounds.height / 2, { steps: 8 });
  await page.mouse.up();
  await progress.click();
  expect((await persistedState(page)).tasks.find(task => task.name === name)?.progress).toBe(0);
  expect(writes).toEqual([]);
  page.off('request', observe);

  await recordProgress(page, name, 2, '上午的阅读');
  await page.keyboard.press('Escape');
  const dialog = await recordProgress(page, name, 3, '下午的阅读');
  await expect(dialog.getByRole('article')).toHaveCount(2);
  await expect(dialog).toBeVisible();
  await expect.poll(async () => (await persistedState(page)).stats.xp).toBe(100);
  const afternoonLabel = (await dialog.getByRole('article').filter({ hasText: '下午的阅读' }).getAttribute('aria-label'))!;
  const afternoon = dialog.getByRole('article', { name: afternoonLabel, exact: true });
  await afternoon.getByRole('button', { name: '编辑记录', exact: true }).click();
  await afternoon.getByLabel('修改完成量', { exact: true }).fill('1');
  await afternoon.getByLabel('修改备注', { exact: true }).fill('修正后的阅读量');
  await afternoon.getByRole('button', { name: '保存修改', exact: true }).click();
  await expect(dialog.getByRole('article').filter({ hasText: '修正后的阅读量' })).toBeVisible();
  await expect.poll(async () => (await persistedState(page)).tasks.find(task => task.name === name)?.progress).toBe(3);
  expect((await persistedState(page)).stats.xp).toBe(0);
  await dialog.getByRole('article').filter({ hasText: '上午的阅读' }).getByRole('button', { name: '撤销记录', exact: true }).click();
  await expect(dialog.getByRole('article')).toHaveCount(1);
  await page.keyboard.press('Escape');
  await expect(progress).toHaveAttribute('aria-valuenow', '1');
  await page.reload();
  await expect(taskCard(page, name).getByRole('progressbar', { name: `${name}总进度`, exact: true })).toHaveAttribute('aria-valuenow', '1');
  const reopened = await openRecords(page, name);
  await expect(reopened.getByRole('article')).toHaveCount(1);
  await expect(reopened).toContainText('修正后的阅读量');
});

test('directory import preserves natural order and mouse marquee toggles mixed and completed selections', async ({ page }) => {
  const name = uniqueName('文件夹课程');
  await page.getByRole('button', { name: '添加任务', exact: true }).click();
  const dialog = page.getByRole('dialog', { name: '从一个小目标开始' });
  await dialog.getByRole('button', { name: /^课程学习/ }).click();
  await dialog.getByLabel('任务名称', { exact: true }).fill(name);
  await dialog.locator('input[webkitdirectory]').setInputFiles(path.join(__dirname, 'fixtures/directory-course'));
  await expect(dialog).toContainText('3 节课程');
  await dialog.getByRole('button', { name: '创建任务', exact: true }).click();
  await expect(dialog).toBeHidden();
  const card = taskCard(page, name);
  await expect(card).toContainText('0 / 3 节');
  const state = await persistedState(page);
  expect(state.tasks[0].course_items?.map(item => item.name)).toEqual(['01 Introduction', 'Basics/', '02 Practice', '10 Recap']);
  const drawer = await openCourse(page, name);
  await drawer.getByText('01 Introduction', { exact: true }).click();
  await expect(card).toContainText('1 / 3 节');
  await drawer.getByRole('button', { name: 'Basics 0/2', exact: true }).click();

  async function marquee(expectedProgress: number) {
    const course = drawer.locator('.course-items');
    await course.scrollIntoViewIfNeeded();
    const bounds = (await course.boundingBox())!;
    const rectangles = await course.locator('[data-course-item]').evaluateAll(elements => elements.map(element => {
      const rect = element.getBoundingClientRect();
      return { right: rect.right, bottom: rect.bottom };
    }));
    await page.mouse.move(bounds.x + 1, bounds.y + 1);
    await page.mouse.down();
    await page.mouse.move(Math.max(...rectangles.map(rect => rect.right)) + 2, Math.max(...rectangles.map(rect => rect.bottom)) + 2, { steps: 12 });
    await expect(course.locator('[data-course-item].outline')).toHaveCount(3);
    await page.mouse.up();
    await expect.poll(async () => (await persistedState(page)).tasks.find(task => task.name === name)?.progress).toBe(expectedProgress);
    await expect(drawer).toBeVisible();
  }

  await marquee(3);
  await expect(drawer).toContainText('课程已完成');
  // Keep the drawer and expanded groups mounted when the dashboard folds this task.
  await expect(drawer.getByRole('button', { name: 'Basics 2/2', exact: true })).toHaveAttribute('aria-expanded', 'true');
  await marquee(0);
  await expect(card).toContainText('0 / 3 节');
});
